#!/usr/bin/env bash

set -e

# Function to build Docker images
build_image() {
  backend=$1
  base_image=$2
  echo "Building image for backend: $backend, base image: $base_image"
  ./build --backend "$backend" --base-image "$base_image"
}

# Function to push Docker images
push_image() {
  image_name=$1
  echo "Pushing image: $image_name"
  docker push "$image_name"
}

# Build images
build_image "stable-fast-qr-code" "saladtechnologies/stable-fast-qr-code:0.5.0-baked"
build_image "stable-fast-qr-code" "saladtechnologies/stable-fast-qr-code:0.5.0"
build_image "sdnext" "saladtechnologies/sdnext:122143-128713"
build_image "sdnext" "saladtechnologies/sdnext:dynamic"
build_image "a1111" "saladtechnologies/a1111:122143-128713"
build_image "a1111" "saladtechnologies/a1111:dynamic"
build_image "comfy" "saladtechnologies/comfyui:baked"
build_image "comfy" "saladtechnologies/comfyui:dynamic"

# Push images
push_image "saladtechnologies/stable-fast-qr-code:worker0.1.0-0.5.0-baked"
push_image "saladtechnologies/stable-fast-qr-code:worker0.1.0-0.5.0"
push_image "saladtechnologies/sdnext:worker0.1.0-122143-128713"
push_image "saladtechnologies/sdnext:worker0.1.0-dynamic"
push_image "saladtechnologies/a1111:worker0.1.0-122143-128713"
push_image "saladtechnologies/a1111:worker0.1.0-dynamic"
push_image "saladtechnologies/comfyui:worker0.1.0-baked"
push_image "saladtechnologies/comfyui:worker0.1.0-dynamic"

echo "Build and push process completed!"
